apiVersion: v1
kind: Pod
metadata:
  labels:
    app: employees
  name: employees
spec:
  containers:
  - image: 914379829654.dkr.ecr.us-east-1.amazonaws.com/web_app:v0.2
    name: employees
    env:
    - name: DBHOST
      value: 10.244.0.5
    - name: DBPORT
      value: "3306"  
    - name: DBUSER
      value: root
    - name: DATABASE
      value: employees
    - name: DBPWD
      value: pw
    - name: APP_COLOR
      value: blue  
    ports:
    - containerPort: 8080
